[2022-07-19 06:46:11,710] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-07-19T06:46:07.455404+00:00 [queued]>
[2022-07-19 06:46:11,724] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-07-19T06:46:07.455404+00:00 [queued]>
[2022-07-19 06:46:11,725] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 06:46:11,726] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-19 06:46:11,726] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 06:46:11,745] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_after_loop> on 2022-07-19 06:46:07.455404+00:00
[2022-07-19 06:46:11,750] {standard_task_runner.py:52} INFO - Started process 246 to run task
[2022-07-19 06:46:11,755] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'manual__2022-07-19T06:46:07.455404+00:00', '--job-id', '28', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpijt1m082', '--error-file', '/tmp/tmpnj_7ik72']
[2022-07-19 06:46:11,756] {standard_task_runner.py:80} INFO - Job 28: Subtask run_after_loop
[2022-07-19 06:46:11,828] {task_command.py:370} INFO - Running <TaskInstance: example_bash_operator.run_after_loop manual__2022-07-19T06:46:07.455404+00:00 [running]> on host 6fab1d40a0c4
[2022-07-19 06:46:11,915] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T06:46:07.455404+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-19T06:46:07.455404+00:00
[2022-07-19 06:46:11,917] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-19 06:46:11,918] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2022-07-19 06:46:11,930] {subprocess.py:85} INFO - Output:
[2022-07-19 06:46:11,931] {subprocess.py:92} INFO - 1
[2022-07-19 06:46:11,932] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-19 06:46:11,975] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20220719T064607, start_date=20220719T064611, end_date=20220719T064611
[2022-07-19 06:46:12,048] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-19 06:46:12,109] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
