[2022-07-19 09:33:10,442] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: simple_dag.respond scheduled__2022-07-19T09:32:00+00:00 [queued]>
[2022-07-19 09:33:10,450] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: simple_dag.respond scheduled__2022-07-19T09:32:00+00:00 [queued]>
[2022-07-19 09:33:10,450] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 09:33:10,451] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-19 09:33:10,451] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 09:33:10,468] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): respond> on 2022-07-19 09:32:00+00:00
[2022-07-19 09:33:10,473] {standard_task_runner.py:52} INFO - Started process 4829 to run task
[2022-07-19 09:33:10,475] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'respond', 'scheduled__2022-07-19T09:32:00+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpwim12a2z', '--error-file', '/tmp/tmpd0tvaaq2']
[2022-07-19 09:33:10,476] {standard_task_runner.py:80} INFO - Job 235: Subtask respond
[2022-07-19 09:33:10,537] {task_command.py:370} INFO - Running <TaskInstance: simple_dag.respond scheduled__2022-07-19T09:32:00+00:00 [running]> on host 02ffb48252da
[2022-07-19 09:33:10,816] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T09:32:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-19T09:32:00+00:00
[2022-07-19 09:33:10,832] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 22, in respond
    "/opt/airflow/dags/20181101_d7_1000_1030.csv", delimiter=";"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1091 fields in line 3, saw 1631

[2022-07-19 09:33:10,867] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=respond, execution_date=20220719T093200, start_date=20220719T093310, end_date=20220719T093310
[2022-07-19 09:33:10,893] {standard_task_runner.py:97} ERROR - Failed to execute job 235 for task respond (Error tokenizing data. C error: Expected 1091 fields in line 3, saw 1631
; 4829)
[2022-07-19 09:33:10,931] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-19 09:33:11,025] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
